### PR TITLE
Move tests

### PR DESCRIPTION
**Pull request by kl0tl**
Otherwise they add an unwanted dependency on quickcheck and quickcheck-laws to dependents, see the build failure of https://github.com/purescript-contrib/purescript-css/pull/125.

### CODE REVIEW

**Review by thomashoneyman — APPROVED** [review]

**Comment by kritzcreek** [comment]
I don't think this is correct. These modules are supposed to let you check that your own `Align` instances are law abiding, but that means you need to be able to import them. By moving them into the `test` directory the spago globs will no longer include them.

Maybe the solution is to move them into a `these-laws`? What's so bad about incurring a quickcheck dependency?

**Comment by thomashoneyman** [comment]
Mm. I misinterpreted these, in that case (sorry @vladciobanu!). We can instead put them back in the prior location and add the quickcheck dependency to the main set of dependencies, that's fine with me. (We'll have to update the package set once again, unfortunately @kl0tl).

**Comment by kl0tl** [comment]
Oh crap, I completely missed the point of these modules 🤦 It seems that they’re usually defined in quickcheck-laws instead though, is there a reason for not following the precedent here?

**Comment by thomashoneyman** [comment]
Maybe we could check in with @vladciobanu quickly and see what he thinks. I don’t have a firm opinion on this.

**Comment by eviefp** [comment]
Well, I didn't think `quickcheck-laws` would want to depend on this, which is why I added them here. It would also make sense for people to just depend on this, since they *have* to import it in order to define the instance in the first place.

**Comment by kl0tl** [comment]
I opened https://github.com/purescript-contrib/purescript-these/pull/33 and https://github.com/purescript/package-sets/pull/762.

**Pull request merged**
