### PR TITLE
Add comments

### PR DESCRIPTION
**Pull request by paf31**
@puffnfresh Does this look ok?

### CODE REVIEW

**Comment by puffnfresh** [comment]
No preference. Parametricity does a really good job of describing most of the functions exactly, doctests would be pretty useful, though.

**Comment by paf31** [comment]
> Parametricity does a really good job of describing most of the functions exactly

For those who understand parametricity, I'd agree, but I think some comments could help beginners. I would add some code examples but I haven't fully understood the usefulness of the class yet.

> doctests would be pretty useful, though.

Agreed.

**Comment by garyb** [comment]
Comments look good to me, perhaps the only thing I'd suggest is being clearer what is meant by the left or right side (like "the `This` value or left side of a `Both`" or something like that) for `theseLeft` and `theseRight`.

Sorry, I didn't notice this PR when I made the updates the other day.

**Comment by garyb** [comment]
Bump for rebase? :smiley:

**Pull request closed without merging**
