### PR TITLE
Update according to Contributors library guidelines

### PR DESCRIPTION
**Pull request by JordanMartinez**
This pull request is part of an effort to update and standardize the Contributors libraries according to the [Library Guidelines](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md). Specifically, it:

1. Adjusts the files and repository structure according to the [repository structure](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md#repository-structure) section of the guidelines, which includes standard pr templates, issue templates, CI in GitHub Actions, automatic stale issue management, ensures the project uses Spago, and so on.
2. Updates the README and documentation according to the [documentation](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md#documentation) section of the guidelines. This is a first step towards ensuring Contributors libraries have adequate module documentation, READMEs, a docs directory, and tests (even if just usage examples) in a `test` directory.
3. Updates labels where relevant to help folks better sift through issues on this library and get started contributing.

This PR is the groundwork for followup efforts to ensure contributor libraries are kept up-to-date, documented, tested, and accessible to users and new contributors.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Maybe we should add the backups directory to the gitignore 😅

**Comment by JordanMartinez** [comment]
Nah... It's helpful when reviewing things one last time. I just forgot to remove those.

**Comment by JordanMartinez** [comment]
I think the only issue that can be opened on this repo is adding more docs. Would you mind if I just add that here rather than open a new PR for it?

Docs would include:
- clarifying what the `These` type is (basically reuse the readme's description)
- documenting what the instances do by providing examples

**Comment by thomashoneyman** [comment]
If you have docs you’d like to add definitely feel free to add them as part of this update. If you would rather wait, open an issue, and open a pr later as a follow up that’s also perfectly fine. Just let me know what you’re thinking so I don’t merge prematurely!

**Comment by JordanMartinez** [comment]
Hm... In that case, let's just merge this PR and I'll add that later.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
